<a href="https://colab.research.google.com/github/MatthewSmith22/BigDataTechnologyHW/blob/master/MatthewSmith_HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score, cross_validate, GridSearchCV
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier

# **Problem 1**

# Part 1 
Import the Auto MPG dataset using Pandas, use the attribute names as explained in the dataset description as the column names, view the strings ‘?’ as the missing value, and whitespace as the column delimiter. Print the first 5 rows and a DataFrame summary.

In [0]:
auto = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data', sep= ' ', header = None,
                   names = ['mpg', 'cylinders', 'displacement', 'horsepower', 'weight', 'acceleration', 'model_year', 'origin'],
                   skipinitialspace = True, na_values = '?', comment = '\t')

In [0]:
auto.head()

mpg  cylinders  displacement  ...  acceleration  model_year  origin
0  18.0          8         307.0  ...          12.0          70       1
1  15.0          8         350.0  ...          11.5          70       1
2  18.0          8         318.0  ...          11.0          70       1
3  16.0          8         304.0  ...          12.0          70       1
4  17.0          8         302.0  ...          10.5          70       1

[5 rows x 8 columns]

# Part 2
Delete the 'name' column as it it irrelevant to the prediction. Print out the shape.

In [0]:
auto.shape

(398, 8)

# Part 3 
Replace the NULL value with the mean value of the column using fill.na(). Print out the DataFrame summary.

In [0]:
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [0]:
hp_mean = auto['horsepower'].mean()
auto['horsepower'].fillna(hp_mean, inplace = True)

In [0]:
auto.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model_year      0
origin          0
dtype: int64

In [0]:
auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64  
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    float64
 4   weight        398 non-null    float64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64  
 7   origin        398 non-null    int64  
dtypes: float64(5), int64(3)
memory usage: 25.0 KB


# Part 4
Convert 'origin' column with ordinal categorical variable into numeric one using get_dummies or OneHotEncoder in Scikit-Learn.

In [0]:
dummy = pd.get_dummies(auto['origin'], prefix='origin')
auto = pd.concat([auto, dummy], axis= 1)

In [0]:
auto.head()

mpg  cylinders  displacement  ...  origin_1  origin_2  origin_3
0  18.0          8         307.0  ...         1         0         0
1  15.0          8         350.0  ...         1         0         0
2  18.0          8         318.0  ...         1         0         0
3  16.0          8         304.0  ...         1         0         0
4  17.0          8         302.0  ...         1         0         0

[5 rows x 11 columns]

In [0]:
auto2 = auto.drop(['origin'], axis=1)

In [0]:
auto2.shape

(398, 10)

In [0]:
auto2.head()

mpg  cylinders  displacement  ...  origin_1  origin_2  origin_3
0  18.0          8         307.0  ...         1         0         0
1  15.0          8         350.0  ...         1         0         0
2  18.0          8         318.0  ...         1         0         0
3  16.0          8         304.0  ...         1         0         0
4  17.0          8         302.0  ...         1         0         0

[5 rows x 10 columns]

# Part 5
Learn a linear regression model to predict the 'mpg' column using the remaining columns.

In [0]:
X_auto = auto2.drop('mpg', axis = 1)
X_auto.shape

(398, 9)

In [0]:
y_auto = auto2['mpg']
y_auto.shape

(398,)

a. Split the data into a training set (80%) and a testing set (20%)

In [0]:
Xtrain, Xtest, ytrain, ytest = train_test_split(X_auto, y_auto, random_state = 1, train_size = 0.8)

b. Train the model using the training set and view the coefficients of the model

In [0]:
lr_model = LinearRegression(fit_intercept=True)

In [0]:
lr_model.fit(Xtrain, ytrain)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
lr_model.coef_

array([-0.29983858,  0.02326461, -0.01685459, -0.00698328,  0.10963199,
        0.82951012, -1.83338998,  0.99553538,  0.8378546 ])

c. Use the learned model to predict on the test set and get the mean squared error for the prediction

In [0]:
y_pred = lr_model.predict(Xtest)

In [0]:
mean_squared_error(ytest, y_pred)

7.616647458934944

# **Problem 2**

# Part 1
Import the red wine dataset using Pandas, use the semi-colon as the column delimiter, and print out both the first five rows and a DataFrame summary.

In [0]:
red_wine = pd.read_csv('http://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv',
                       sep = ';')

In [0]:
red_wine.head()

fixed acidity  volatile acidity  citric acid  ...  sulphates  alcohol  quality
0            7.4              0.70         0.00  ...       0.56      9.4        5
1            7.8              0.88         0.00  ...       0.68      9.8        5
2            7.8              0.76         0.04  ...       0.65      9.8        5
3           11.2              0.28         0.56  ...       0.58      9.8        6
4            7.4              0.70         0.00  ...       0.56      9.4        5

[5 rows x 12 columns]

In [0]:
red_wine.shape

(1599, 12)

In [0]:
red_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


# Part 2
Suppose we want to predict the quality of wine based on other attibutes. Divide data into label and feature sets. Then split the data into a training set (80%) and a testing set (20%) using train_test_split.

In [0]:
X_wine = red_wine.drop('quality', axis=1)
X_wine.shape

(1599, 11)

In [0]:
y_wine = red_wine['quality']
y_wine.shape

(1599,)

In [0]:
X_train, X_test, y_train, y_test = train_test_split(X_wine, y_wine, random_state = 1, train_size = 0.8)

# Part 3
Use the StandardScalar to normalize the data. Note that the testing set can only be scaled by the mean and standard deviation values obtained from the training set.

In [0]:
scaler = StandardScaler().fit(X_train)

In [0]:
scaler.transform(X_train)

array([[-0.73307913,  0.6648928 , -1.25704443, ...,  0.98846046,
         0.0630946 , -0.87223395],
       [ 1.06774091, -0.62346154,  1.52314768, ..., -1.7535127 ,
        -0.17390392, -0.77978452],
       [-1.74604041, -1.07158479, -1.35814232, ...,  2.32756363,
         0.77409018,  3.28799021],
       ...,
       [-0.95818164,  1.08500835, -0.90320179, ...,  0.22325865,
        -1.00339876,  0.32960859],
       [-0.62052788,  0.55286199, -1.35814232, ...,  0.35079228,
        -0.47015208, -1.33448108],
       [ 0.44870902, -0.73549236,  1.16930505, ..., -0.6694768 ,
         0.18159387,  1.90124882]])

In [0]:
scaler.transform(X_test)

array([[ 0.27988214, -0.67947695,  1.87699031, ...,  1.43482818,
         0.00384497,  0.05226031],
       [ 0.22360652,  0.55286199,  0.05722821, ..., -0.35064271,
        -0.17390392, -0.22508797],
       [ 1.18029216, -1.07158479,  1.57369663, ..., -0.79701044,
         0.2408435 ,  0.79185571],
       ...,
       [-0.67680351,  0.77692361, -1.35814232, ...,  0.79716001,
        -0.7071506 , -0.96468337],
       [-1.18328414, -0.79150776,  0.81546242, ...,  0.86092682,
         1.24808723,  0.69940629],
       [ 1.4616703 , -1.18361561,  1.27040294, ..., -0.22310908,
         0.65559092,  0.97675456]])

# Part 4
Use the RandomForestClassifier (with 300 trees) as the classification model in Scikit_Learn. Use 5-fold cross validation to train and cross-validate the model. Print the accuracies returned by the five folds as well as their average and standard deviation values.

In [0]:
rf_model = RandomForestClassifier(n_estimators= 300, random_state= 1)

In [0]:
cv_score = cross_val_score(rf_model, X_train, y_train, cv= 5)

In [0]:
cv_score

array([0.671875  , 0.66015625, 0.71875   , 0.67578125, 0.66666667])

In [0]:
cv_score.mean()

0.6786458333333333

In [0]:
cv_score.std()

0.020725633074032856

# Part 5
Use GridSearchCV to find the best hyperparameter for the number of trees (try the following values: 100, 300, 500, 800, 1000 for 'n_estimator').

In [0]:
parameters = {'n_estimators':[100, 300, 500, 800, 1000]}
clf = GridSearchCV(rf_model, parameters, cv = 5)

In [0]:
clf.fit(X_train, y_train)

In [0]:
clf.best_params_

{'n_estimators': 800}

# Part 6
Find the accuracy of the model obatained using the best hyperparmeter value on the testing dataset.

In [0]:
rf_model2 = RandomForestClassifier(n_estimators= 800, random_state= 1)

In [0]:
rf_pred = rf_model2.fit(X_train, y_train)

In [0]:
y_pred = rf_pred.predict(X_test)

In [0]:
accuracy_score(y_test, y_pred)

0.721875